<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/feed/feed.css">
    <link rel="stylesheet" href="./css/feed/publications.css">
    <link rel="stylesheet" href="./css/feed/story.css">
    <link rel="stylesheet" href="./css/feed/lateral.css">
    <link rel="stylesheet" href="./css/feed/media_quieres.css">
</head>
<body>
    
    <main>
    <div id="feed">
             <div id="story">
             <?php foreach($this->view->story as $users){?>
                <div id="story-border">
                   <div id="story-users">
                       <img src="/viewFoto?user=<?= $users['id_usuario'] ?>" alt="">
                   </div>
                </div>
             <?php }  ?>
           
             </div>
             
             <div>
            
             <div class="publications">
               
                <div id="header">
                    <span id="user">
                        <span class="photo-user"><img src="viewFoto?user=<?= $publication['id_usuario']?>" alt=""></span>
                        <a href="#"><?= $publication['nome'] ?></a>
                    </span>

                    <span id="plus">
                     ...
                    </span>
                    
                </div>

                <div id="photo">
                   <img src="https://i.picsum.photos/id/530/536/354.jpg?hmac=NcUoRcnG5YENmSUJpc-ltVYKlVt4f5y6FxF5Cr9yHUE']  ?>" alt="">
                </div>

                <div id="footer">
                    <div id="options">
                        <span id="feedback"> 

                             <button><i style='color:red' class="fas  fa-heart fa-2x"></i></button>
                            
                             <a href="/comments"><button class="wpO6b " type="button"><div class="QBdPU "><svg aria-label="Comentar" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24" data-darkreader-inline-fill="" style="--darkreader-inline-fill:#d0ccc6;"><path clip-rule="evenodd" d="M47.5 46.1l-2.8-11c1.8-3.3 2.8-7.1 2.8-11.1C47.5 11 37 .5 24 .5S.5 11 .5 24 11 47.5 24 47.5c4 0 7.8-1 11.1-2.8l11 2.8c.8.2 1.6-.6 1.4-1.4zm-3-22.1c0 4-1 7-2.6 10-.2.4-.3.9-.2 1.4l2.1 8.4-8.3-2.1c-.5-.1-1-.1-1.4.2-1.8 1-5.2 2.6-10 2.6-11.4 0-20.6-9.2-20.6-20.5S12.7 3.5 24 3.5 44.5 12.7 44.5 24z" fill-rule="evenodd"></path></svg></div></button></a>
        
                             <button class="wpO6b " type="button"><div class="QBdPU "><svg aria-label="Compartilhar publicação" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24" data-darkreader-inline-fill="" style="--darkreader-inline-fill:#d0ccc6;"><path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z"></path></svg></div></button>
                           </span>
        
                            <button class="wpO6b " type="button"><div class="QBdPU B58H7"><svg aria-label="Salvar" class="_8-yf5 " fill="#8e8e8e" height="24" viewBox="0 0 48 48" width="24" data-darkreader-inline-fill="" style="--darkreader-inline-fill:#a1988c;"><path d="M43.5 48c-.4 0-.8-.2-1.1-.4L24 29 5.6 47.6c-.4.4-1.1.6-1.6.3-.6-.2-1-.8-1-1.4v-45C3 .7 3.7 0 4.5 0h39c.8 0 1.5.7 1.5 1.5v45c0 .6-.4 1.2-.9 1.4-.2.1-.4.1-.6.1zM24 26c.8 0 1.6.3 2.2.9l15.8 16V3H6v39.9l15.8-16c.6-.6 1.4-.9 2.2-.9z"></path></svg></div>
        
                    </div>
                    <p>
                       <?= $publication['subtitle'] ?>
                    </p>
                </div>
                <div id="coment">
                  <input type="text" placeholder="Adicione um Comentario">

                  <a href="">Publicar</a>
                </div>
               </div>
             </div>
                    
                </div>
    </main>
    
</body>
</html>